development:
  adapter: postgresql
  database: shelf_development
  pool: 5
  timeout: 5000
  host: localhost
  username: shelfuser
  password: shelf
test:
  adapter: postgresql
  database: shelf_test
  pool: 5
  timeout: 5000
  host: localhost
  username: shelfuser
  password: shelf

production:
  adapter: postgresql
  database: shelf_production
  pool: 5
  timeout: 5000
